targets:
  $default:
    sources:
      include:
        - $package$
        - lib/**
        - pubspec.yaml
        - assets/**
    builders:
      flutter_gen_runner:
        options:
          output: lib/gen/
          integrations:
            flutter_svg: true
          assets:
            exclude:
              - assets/i18n/**
